1. The most basic kind of broadcast is with a scalar, in which you can perform a binary
operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that
operation with the scalar for every element of the array. To try this out, create a vector
1, 2, . . . , 10 by adding 1 to the result of the arange function.


In [4]:
import numpy as np

a = np.arange(1,10+1,1)

b = a + 5
c = a * 5
print(a)
print(b)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]
[ 5 10 15 20 25 30 35 40 45 50]


2. Now, create a 10 × 10 matrix A in which A[i][j] = i + j. You’ll be able to do this using
the vector you just created, and adding it to a reshaped version of itself

In [5]:
import numpy as np

data = np.arange(1,101,1)

hello = data.reshape(10,10)

print(hello)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


3.A very common use of broadcasting is to standardize data, i.e., to make it have zero
mean and unit variance.
a. First, create a fake “data set” with 50 examples, each with five dimensions.
b. import numpy.random as npr
data = np.exp ( npr.randn(50, 5) )
c. Don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number
generation library, then generates a 50 × 5 matrix of standard normal random
variates and exponentiates them. The effect of this is to have a pretend data
set of 50 independent and identically-distributed vectors from a log-normal
distribution.


In [6]:
import numpy.random as npr
import numpy as np
data = np.exp ( npr.randn(50, 5) )

print(data)

[[ 5.18866411  2.352965    1.48376812  0.60539364  9.2302842 ]
 [ 1.59122099  1.6984785   0.42350885  4.40984792  2.4390028 ]
 [ 0.58215418  3.55258143  0.14732735  0.96427607  1.31813292]
 [ 0.32220249 17.44333684  0.851946    0.8164574   0.41064193]
 [ 2.50182313  0.39716984  2.92228589  0.54840963  2.53432058]
 [ 1.69027985  0.51443314  1.31115273  0.23495995 10.19883902]
 [ 1.50453259  1.3074759   1.6758646   7.42835447  0.47914495]
 [ 3.79375233  0.57511265  0.32787424  5.61830812  0.4379874 ]
 [ 0.07894427  2.25566986  2.65404478  1.32116584  0.75722304]
 [ 1.50104579  1.41403358  0.69244101  0.39699319  0.26667283]
 [ 2.79430602  0.53465988  0.23913093  2.363038    4.63705192]
 [ 2.09360892  0.48506786  3.61376358  1.38364853  1.15784539]
 [ 2.33770913  0.31712866  0.8638706   0.29787352  0.64792461]
 [ 0.50706237  2.60281456  3.74812832  1.93391952  1.47529909]
 [ 1.59634454  0.25366582  1.85624731  0.10194781  1.37678102]
 [ 1.94470911  0.20677092  2.81585171  0.39472373  2.73

4.Now, compute the mean and standard deviation of each column. This should result in
two vectors of length 5. You’ll need to think a little bit about how to use the axis
argument to mean and std. Store these vectors into variables and print both of them.


In [7]:
import numpy.random as npr
import numpy as np
data = np.exp ( npr.randn(50, 5) )

mean_col = np.mean(data,axis=0)
print(mean_col)
std_col = np.std(data,axis=0)
print(std_col)

[1.50941384 1.57327682 1.95032629 1.24619085 1.84911509]
[1.26835576 1.8869329  2.18906068 1.21639885 2.75330746]


5.Now standardize the data matrix by 1) subtracting the mean off of each column, and
2)dividing each column by its standard deviation. Do this via broadcasting, and store
the result in a matrix called normalized. To verify that you successfully did it, compute
the mean and standard deviation of the columns of normalized and print them out.

In [ ]:
import numpy.random as npr
import numpy as np
data = np.exp ( npr.randn(50, 5) )

mean_col = np.mean(data,axis=0)
print(mean_col)
std_col = np.std(data,axis=0)
print(std_col)

normalized = (data - mean_col) / std_col
print(normalized)


#alternative method
'''normalised = (data - np.mean(data, axis=0)) / np.std(data, axis=0)
print(normalised)'''

mean_of_normalized = np.mean(normalized,axis = 0)
print(mean_of_normalized)

std_of_normalized = np.std(normalized,axis = 0)
print(std_of_normalized)

Aim: Performing the Hypothesis testing using the Chi-squared test
The table below is a survey response to 4 categorical variables: people in categories from
18–29, 30–44, 45–64 and >65 years, and their movie genre inclination, which is
“Action/Adventure”, “Romance” and “Biography”. Is there any evidence of a relationship
between the age group and their movie genre inclination, at 5% significance level?

In [3]:
import pandas as pd
import scipy.stats as stats

# create sample data according to survey
data = [['18-29', 'Action/Adventure'] for i in range(141)] + \
        [['18-29', ' Romance '] for i in range(68)] + \
        [['18-29', 'Biography'] for i in range(4)] + \
        [['30-44', 'Action/Adventure'] for i in range(179)] + \
        [['30-44', ' Romance '] for i in range(159)] + \
        [['30-44', 'Biography'] for i in range(7)] + \
        [['45-65', 'Action/Adventure'] for i in range(220)] + \
        [['45-65', ' Romance '] for i in range(216)] + \
        [['45-65', 'Biography'] for i in range(4)] + \
        [['65 & older', 'Action/Adventure'] for i in range(86)] + \
        [['65 & older', ' Romance '] for i in range(101)] + \
        [['65 & older', 'Biography'] for i in range(4)]
df = pd.DataFrame(data, columns = ['Age Group', 'Genre']) 

# create contingency table
data_crosstab = pd.crosstab(df['Age Group'],
                            df['Genre'],
                           margins=True, margins_name="Total")


# significance level
alpha = 0.05

# Calcualtion of Chisquare
chi_square = 0
rows = df['Age Group'].unique()
columns = df['Genre'].unique()
for i in columns:
    for j in rows:
        O = data_crosstab[i][j]
        E = data_crosstab[i]['Total'] * data_crosstab['Total'][j] / data_crosstab['Total']['Total']
        chi_square += (O-E)**2/E

# The p-value approach
p_value = 1 - stats.chi2.cdf(chi_square, (len(rows)-1)*(len(columns)-1))
conclusion = "Failed to reject the null hypothesis."
if p_value <= alpha:
    conclusion = "Null Hypothesis is rejected."
        
print("chi square-score is:", chi_square)
print('p value is',p_value)
print(conclusion)


chi square-score is: 24.367421717305202
p value is 0.0004469083391495099
Null Hypothesis is rejected.
